Repository zeoflow/material-elements, pull requests merged in 2020-10, with the labels that each got.

#35 Loading Button: new Elements
  material-elements/java/com/zeoflow/material/elements/button/MaterialButtonLoading.java
  material-elements/java/com/zeoflow/material/elements/button/res/font/zeoflow_regular.ttf
  material-elements/java/com/zeoflow/material/elements/button/res/layout/loading_button.xml
  material-elements/java/com/zeoflow/material/elements/button/res/values/attrs.xml
  material-elements/java/com/zeoflow/material/elements/button/res/values/bools.xml
  material-elements/java/com/zeoflow/material/elements/button/res/values/dimens.xml
  sample/src/main/res/font/zeoflow_regular.ttf
  sample/src/main/res/layout/activity_main.xml
  sample/src/main/res/values/styles.xml
Labels: @feature, @priority-medium

#36 Updated Material Button
  material-elements/java/com/zeoflow/material/elements/button/MaterialButton.java
  material-elements/java/com/zeoflow/material/elements/button/MaterialButtonLoading.java
  material-elements/java/com/zeoflow/material/elements/button/res/values/attrs.xml
  material-elements/java/com/zeoflow/material/elements/theme/res/values/themes.xml
  sample/src/main/res/layout/activity_main.xml
Labels: @bug-fix, @enhancement

#38 MaterialButtonLoading OnClickListener
  .zeobot/config.yml
  material-elements/gradle.properties
  material-elements/java/com/zeoflow/material/elements/button/MaterialButtonLoading.java
  sample/src/main/java/com/zeoflow/core/sample/MainActivity.kt
  sample/src/main/res/layout/activity_main.xml
Labels: @bug-fix, @priority-medium

#41 created CircleImageView
  build.gradle
  material-elements/gradle.properties
  material-elements/java/com/zeoflow/material/elements/animation/AnimationUtils.java
  material-elements/java/com/zeoflow/material/elements/animation/AnimatorSetCompat.java
  material-elements/java/com/zeoflow/material/elements/animation/ArgbEvaluatorCompat.java
  material-elements/java/com/zeoflow/material/elements/animation/ChildrenAlphaProperty.java
  material-elements/java/com/zeoflow/material/elements/imageview/CircleImageView.java
  material-elements/java/com/zeoflow/material/elements/imageview/res/values/attrs.xml
  sample/build.gradle
  sample/src/main/AndroidManifest.xml
  sample/src/main/assets/animation.json
  sample/src/main/java/com/zeoflow/core/sample/MainActivity.kt
  sample/src/main/java/com/zeoflow/material/elements/sample/MainActivity.java
  sample/src/main/res/drawable/ic_launcher_background.xml
  sample/src/main/res/drawable/ic_launcher_foreground.xml
  sample/src/main/res/font/zeoflow_regular.ttf
  sample/src/main/res/layout/activity_main.xml
  sample/src/main/res/values/colors.xml
  sample/src/main/res/values/styles.xml
Labels: @feature, @issue, @priority-medium

#42 created AutoFitEditText
  material-elements/java/com/zeoflow/material/elements/textfield/AutoFitEditText.java
  material-elements/java/com/zeoflow/material/elements/textfield/AutoFitEditTextUtil.java
  material-elements/java/com/zeoflow/material/elements/textview/AutosizeTextView.java
  material-elements/java/com/zeoflow/material/elements/textview/res/values/attrs.xml
  sample/build.gradle
  sample/src/main/res/layout/activity_main.xml
Labels: @feature, @issue, @priority-high

#43 Created ColorWheel and GradientSeekbar
  .zeobot/config.yml
  build.gradle
  material-elements/build.gradle
  material-elements/gradle.properties
  material-elements/java/com/zeoflow/material/elements/animation/FadeUtils.java
  material-elements/java/com/zeoflow/material/elements/animation/res/anim/fade_in.xml
  material-elements/java/com/zeoflow/material/elements/animation/res/anim/fade_out.xml
  material-elements/java/com/zeoflow/material/elements/button/MaterialButton.java
  material-elements/java/com/zeoflow/material/elements/button/MaterialButtonLoading.java
  material-elements/java/com/zeoflow/material/elements/button/res/layout/loading_button.xml
  material-elements/java/com/zeoflow/material/elements/color/ColorEnvelope.java
  material-elements/java/com/zeoflow/material/elements/color/ColorUtils.java
  material-elements/java/com/zeoflow/material/elements/colorwheel/ColorWheel.kt
  material-elements/java/com/zeoflow/material/elements/colorwheel/build.gradle
  material-elements/java/com/zeoflow/material/elements/colorwheel/extensions/ParcelExtensions.kt
  material-elements/java/com/zeoflow/material/elements/colorwheel/flag/BubbleFlag.java
  material-elements/java/com/zeoflow/material/elements/colorwheel/flag/FlagMode.java
  material-elements/java/com/zeoflow/material/elements/colorwheel/flag/FlagView.java
  material-elements/java/com/zeoflow/material/elements/colorwheel/res/drawable/ic_bubble_big.xml
  material-elements/java/com/zeoflow/material/elements/colorwheel/res/drawable/ic_bubble_small.xml
  material-elements/java/com/zeoflow/material/elements/colorwheel/res/drawable/wheel.png
  material-elements/java/com/zeoflow/material/elements/colorwheel/res/layout/flag_bubble.xml
  material-elements/java/com/zeoflow/material/elements/colorwheel/res/values/attrs.xml
  material-elements/java/com/zeoflow/material/elements/colorwheel/res/values/colors.xml
  material-elements/java/com/zeoflow/material/elements/colorwheel/res/values/styles.xml
  material-elements/java/com/zeoflow/material/elements/colorwheel/res/values/values.xml
  material-elements/java/com/zeoflow/material/elements/colorwheel/thumb/ThumbDrawable.kt
  material-elements/java/com/zeoflow/material/elements/colorwheel/thumb/ThumbDrawableState.kt
  material-elements/java/com/zeoflow/material/elements/colorwheel/utils/ColorUtils.kt
  material-elements/java/com/zeoflow/material/elements/colorwheel/utils/HsvColor.kt
  material-elements/java/com/zeoflow/material/elements/colorwheel/utils/MathUtils.kt
  material-elements/java/com/zeoflow/material/elements/colorwheel/utils/TouchUtils.kt
  material-elements/java/com/zeoflow/material/elements/gradientseekbar/GradientSeekBar.kt
  material-elements/java/com/zeoflow/material/elements/gradientseekbar/HorizontalStrategy.kt
  material-elements/java/com/zeoflow/material/elements/gradientseekbar/OrientationStrategy.kt
  material-elements/java/com/zeoflow/material/elements/gradientseekbar/VerticalStrategy.kt
  material-elements/java/com/zeoflow/material/elements/gradientseekbar/build.gradle
  material-elements/java/com/zeoflow/material/elements/gradientseekbar/res/values/attrs.xml
  material-elements/java/com/zeoflow/material/elements/gradientseekbar/res/values/styles.xml
  material-elements/java/com/zeoflow/material/elements/imageview/CircleImageView.java
  material-elements/java/com/zeoflow/material/elements/imageview/MaterialImageView.java
  material-elements/java/com/zeoflow/material/elements/textfield/AutoFitEditText.java
  material-elements/java/com/zeoflow/material/elements/textfield/ClearTextEndIconDelegate.java
  material-elements/java/com/zeoflow/material/elements/textfield/DropdownMenuEndIconDelegate.java
  sample/src/main/java/com/zeoflow/material/elements/sample/MainActivity.java
  sample/src/main/res/layout/activity_main.xml
Labels: @new, @priority-high

#44 Created SlidingUpPanel
  material-elements/build.gradle
  material-elements/java/com/zeoflow/material/elements/animation/FadeUtils.java
  material-elements/java/com/zeoflow/material/elements/animation/res/anim/fade_in.xml
  material-elements/java/com/zeoflow/material/elements/animation/res/anim/fade_out.xml
  material-elements/java/com/zeoflow/material/elements/color/ColorEnvelope.java
  material-elements/java/com/zeoflow/material/elements/color/ColorUtils.java
  material-elements/java/com/zeoflow/material/elements/colorwheel/ColorWheel.kt
  material-elements/java/com/zeoflow/material/elements/colorwheel/flag/BubbleFlag.java
  material-elements/java/com/zeoflow/material/elements/colorwheel/flag/FlagMode.java
  material-elements/java/com/zeoflow/material/elements/colorwheel/flag/FlagView.java
  material-elements/java/com/zeoflow/material/elements/colorwheel/res/drawable/ic_bubble_big.xml
  material-elements/java/com/zeoflow/material/elements/colorwheel/res/drawable/ic_bubble_small.xml
  material-elements/java/com/zeoflow/material/elements/slidingpanel/ScrollableViewHelper.java
  material-elements/java/com/zeoflow/material/elements/slidingpanel/SlidingUpPanelLayout.java
  material-elements/java/com/zeoflow/material/elements/slidingpanel/ViewDragHelper.java
  material-elements/java/com/zeoflow/material/elements/slidingpanel/build.gradle
  material-elements/java/com/zeoflow/material/elements/slidingpanel/res/drawable/above_shadow.xml
  material-elements/java/com/zeoflow/material/elements/slidingpanel/res/drawable/below_shadow.xml
  material-elements/java/com/zeoflow/material/elements/slidingpanel/res/values/attrs.xml
  material-elements/java/com/zeoflow/material/elements/textfield/ClearTextEndIconDelegate.java
  material-elements/java/com/zeoflow/material/elements/textfield/DropdownMenuEndIconDelegate.java
  sample/src/main/java/com/zeoflow/material/elements/sample/MainActivity.java
  sample/src/main/res/layout/activity_main.xml
Labels: @new, @priority-high

#45 Created PagerIndicator
  material-elements/build.gradle
  material-elements/java/com/zeoflow/material/elements/pagerindicator/AbstractViewPagerAttacher.java
  material-elements/java/com/zeoflow/material/elements/pagerindicator/RecyclerViewAttacher.java
  material-elements/java/com/zeoflow/material/elements/pagerindicator/ScrollingPagerIndicator.java
  material-elements/java/com/zeoflow/material/elements/pagerindicator/ViewPager2Attacher.java
  material-elements/java/com/zeoflow/material/elements/pagerindicator/ViewPagerAttacher.java
  material-elements/java/com/zeoflow/material/elements/pagerindicator/build.gradle
  material-elements/java/com/zeoflow/material/elements/pagerindicator/res/values/attrs.xml
  material-elements/java/com/zeoflow/material/elements/pagerindicator/res/values/styles.xml
  sample/src/main/res/layout/activity_main.xml
Labels: @new, @priority-medium

#49 Added SquareView
  build.gradle
  material-elements/build.gradle
  material-elements/java/com/zeoflow/material/elements/square/SquareView.java
  material-elements/java/com/zeoflow/material/elements/square/build.gradle
  sample/src/main/java/com/zeoflow/material/elements/sample/MainActivity.java
Labels: @feature, @issue, @priority-low

#50 ColorWheel Private Access
  material-elements/java/com/zeoflow/material/elements/colorwheel/ColorWheel.kt
  material-elements/java/com/zeoflow/material/elements/colorwheel/thumb/ThumbDrawable.kt
  material-elements/java/com/zeoflow/material/elements/colorwheel/thumb/ThumbDrawableState.kt
  sample/src/main/java/com/zeoflow/material/elements/sample/MainActivity.java
  sample/src/main/res/layout/activity_main.xml
Labels: @bug-fix, @issue, @priority-high

#52 Created PhotoView
  build.gradle
  material-elements/build.gradle
  material-elements/gradle.properties
  material-elements/java/com/zeoflow/material/elements/photoview/Compat.java
  material-elements/java/com/zeoflow/material/elements/photoview/CustomGestureDetector.java
  material-elements/java/com/zeoflow/material/elements/photoview/OnGestureListener.java
  material-elements/java/com/zeoflow/material/elements/photoview/OnMatrixChangedListener.java
  material-elements/java/com/zeoflow/material/elements/photoview/OnOutsidePhotoTapListener.java
  material-elements/java/com/zeoflow/material/elements/photoview/OnPhotoTapListener.java
  material-elements/java/com/zeoflow/material/elements/photoview/OnScaleChangedListener.java
  material-elements/java/com/zeoflow/material/elements/photoview/OnSingleFlingListener.java
  material-elements/java/com/zeoflow/material/elements/photoview/OnViewDragListener.java
  material-elements/java/com/zeoflow/material/elements/photoview/OnViewTapListener.java
  material-elements/java/com/zeoflow/material/elements/photoview/PhotoView.java
  material-elements/java/com/zeoflow/material/elements/photoview/PhotoViewAttacher.java
  material-elements/java/com/zeoflow/material/elements/photoview/Util.java
  material-elements/java/com/zeoflow/material/elements/photoview/build.gradle
  sample/src/main/java/com/zeoflow/material/elements/sample/MainActivity.java
  sample/src/main/res/layout/activity_main.xml
Labels: @feature, @priority-high
